LOCKFILE_PATH = "/tmp/debug_cron_server.lock"
SOCKET_IN_PATH = "/tmp/debug_cron.in"
SOCKET_OUT_PATH = "/tmp/debug_cron.out"
RUN_SIGNAL_PATH = "/tmp/debug_cron_server.runsignal"
LOG_PATH = "/tmp/debug_cron_server.log"
