get_lockfile_path = lambda : "/tmp/debug_cron_server.lock"
get_socket_in_path = lambda : "/tmp/debug_cron.in"
get_socket_out_path = lambda : "/tmp/debug_cron.out"
get_run_signal_path = lambda : "/tmp/debug_cron_server.runsignal"
get_log_path = lambda : "/tmp/debug_cron_server.log"
